[package]
name = "interrupts"
version = "0.1.0"
authors = ["Hanaasagi <ambiguous404@gmail.com>"]

[dependencies]
spin = "0.4.4"
bitflags = "1"

[dependencies.vga]
path = "../vga"

[dependencies.device]
path = "../device"
